### ISSUE TITLE
Anyone can call GUARD.redeemReward() function for any wallet

### ISSUE THREAD

**Issue by k0kk0k** [celer-network/sgn-contract#45]
If the owner of the address left an unclosed limit on the transactions of CELR tokens, then anyone can call the redeemReward() function for this address and withdraw rewards form contract to owner's address without the owner's knowledge and permission.

Example of such transaction in Rinkeby test network: https://rinkeby.etherscan.io/tx/0x537f04ba08dabcbaa2a2f9e30e6cc8ab322af3f75e70c25a00f646d13987656d
Field `from` (0xe9ff965a978dcb878104e49163ccefe7d0679f2b)  differs filed `receiver` (0xdf9db0368fe7eab5247da5c526f88361c0a5ad1e)

**Comment by k0kk0k** [comment]
The simplest solution is to check in the `GUARD.redeemReward()` 
`caller_addr=receiver_addr`

**Comment by stevenlcf** [comment]
Hi @k0kk0k , thank you for your careful code review! Your comment regarding the code behavior is correct but I don't think it will lead to any security issues. Because the security is guaranteed by the signatures in the reward request and all of the rewards can only go to the receiver's account. That being said, all things that a random user can do, essentially, is to help others save gas by calling `redeemReward` for other people, which is not incentive compatible for malicious users.
